# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  - trigger: :;aiack
    replace: (Assisted by Claude Code; any errors are mine.)
  - trigger: :;aiack
    replace: (Partially assisted by Claude Code; any errors are mine.)

  - trigger: :;umgr
    replace: Micro-Manager
  - trigger: :;hcw
    replace: Hardware Configuration Wizard
  - trigger: :;dpb
    replace: Device Property Browser
  - trigger: :;mda
    replace: Multi-Dimensional Acquisition
  - trigger: :;dvi
    replace: Device Interface Version
